version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
      - image: cimg/mariadb:10.6
    steps:
      - checkout
      - run: python3 Paises.py
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
      - image: cimg/mariadb:10.6
    steps:
      - checkout
      - run: python3 test.py

workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build