version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4" # The primary container where steps are run       
      - image: cimg/mariadb:10.6      
        environment:
          MYSQL_DATABASE: "paises_proyecto"
          MYSQL_USER: "root"
          MYSQL_HOST: "localhost"
          MYSQL_PASSWORD: 123

workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
    